title: ferramentas CantoCoral.Net
author: Pedro Vieira
#email: pedro@pedrovieira.com.br
#theme: minima
remote_theme: pmarsceill/just-the-docs

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/pedvieira" }
    - { platform: twitter, user_url: "https://twitter.com/pedrovieira_br" }

#description: > # this means to ignore newlines until "baseurl:"
#Esta é a descrição do site. Aqui é onde explico o resumo do projeto em questão.

# social links
#twitter_username: pedrovieira_br # DO NOT include the @ character, or else the build will fail!
#github_username:  pedvieira # DO NOT include the @ character, or else the build will fail!
